# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-3.4
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4




# version: 2


# jobs:
#   build:
        
#     docker:
#       - image: circleci/python:3.6.1 circleci/python:3.5 circleci/python:3.4
#       # - image: circleci/python:3.5
#       # - image: circleci/python:3.4
#     # machine:
#     #   post:
#     #     - pyenv global 3.6      
#     working_directory: ~/repo

#     steps:
#       - checkout

#       - run:
#           name: install dependencies
#           command: |
#             sudo pip install -r requirements.txt
#             sudo python3 -m venv venv
#             . venv/bin/activate
        
#       # run tests!
#       - run:
#           name: run tests
#           command: |
#             tox