# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

machine:
  post:
    - pyenv global 3.4 3.5 3.6
jobs:
  build:
        
    # docker:
      # - image: circleci/python:3.6.1
      # - image: circleci/python:3.5
      # - image: circleci/python:3.4
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo python3 -m venv venv
            . venv/bin/activate
        
      # run tests!
      - run:
          name: run tests
          command: |
            tox