# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-3.4
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    
    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo python3 -m venv venv
            . venv/bin/activate
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: Run tests
          command: |
            pytest
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4